/**
 * generated by Xtext
 */
package de.unidue.ecg.dialogScript.ui.contentassist;

import de.unidue.ecg.dialogScript.ui.contentassist.AbstractDialogScriptProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DialogScriptProposalProvider extends AbstractDialogScriptProposalProvider {
}
