/**
 * generated by Xtext
 */
package de.unidue.ecg.dialogScript.scoping;

import org.eclipse.xtext.scoping.impl.ImportNormalizer;
import org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider;
import org.eclipse.xtext.util.Strings;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class DialogScriptImportScopeProvider extends ImportedNamespaceAwareLocalScopeProvider {
  protected ImportNormalizer createImportedNamespaceResolver(final String namespace, final boolean ignoreCase) {
    ImportNormalizer _xblockexpression = null;
    {
      String newNamespace = namespace;
      boolean _isEmpty = Strings.isEmpty(namespace);
      boolean _not = (!_isEmpty);
      if (_not) {
        String _plus = (newNamespace + ".*");
        newNamespace = _plus;
      }
      ImportNormalizer _createImportedNamespaceResolver = super.createImportedNamespaceResolver(newNamespace, ignoreCase);
      _xblockexpression = (_createImportedNamespaceResolver);
    }
    return _xblockexpression;
  }
}
