/*
 * generated by Xtext
 */
package de.unidue.ecg.dialogScript.ui;

import org.eclipse.jface.text.templates.ContextTypeRegistry;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.builder.IXtextBuilderParticipant;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalComparator;
import org.eclipse.xtext.ui.editor.contentassist.ITemplateProposalProvider;
import org.eclipse.xtext.ui.resource.IResourceSetProvider;
import org.eclipse.xtext.ui.resource.SimpleResourceSetProvider;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

import de.unidue.ecg.dialogScript.ui.builderParticipant.DialogScriptBuilderParticipant;
import de.unidue.ecg.dialogScript.ui.editor.syntaxcoloring.DialogScriptHighlightingConfiguration;
import de.unidue.ecg.dialogScript.ui.editor.syntaxcoloring.DialogScriptSemanticHighlightingCalculator;
import de.unidue.ecg.common.ui.contentassist.TemplatePreferringCompletionProposalProvider;
import de.unidue.ecg.dialogScript.ui.editor.templates.TerminalRuleAwareTemplateContextTypeRegistry;
import de.unidue.ecg.dialogScript.ui.editor.templates.TerminalRuleAwareTemplateProposalProvider;
import de.unidue.ecg.dialogScript.ui.views.DialogGraphView;
import de.unidue.ecg.dialogScript.ui.wizard.DialogScriptProjectCreator;


/**
 * Use this class to register components to be used within the IDE.
 */
public class DialogScriptUiModule extends de.unidue.ecg.dialogScript.ui.AbstractDialogScriptUiModule {
	public DialogScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	

	
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return DialogScriptProjectCreator.class;
	}
	
	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return DialogScriptHighlightingConfiguration.class;
	}
	
	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator>bindISemanticHighlightingCalculator() {
		return DialogScriptSemanticHighlightingCalculator.class;
	}
	
	@Override
	public Class<? extends ContextTypeRegistry> bindContextTypeRegistry() {
		return TerminalRuleAwareTemplateContextTypeRegistry.class;
	}
	
	@Override
	public Class<? extends ITemplateProposalProvider> bindITemplateProposalProvider() {
		return TerminalRuleAwareTemplateProposalProvider.class;
	}
	
	public Class<? extends ICompletionProposalComparator> bindICompletionProposalComparator() {
		return TemplatePreferringCompletionProposalProvider.class;
	}
	
	@Override
	public Class<? extends IResourceSetProvider> bindIResourceSetProvider() {
		return SimpleResourceSetProvider.class;
	}
	
	@Override
	public Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		return DialogScriptBuilderParticipant.class;
	}
	
	public Class<DialogGraphView> bindDialogGraphView() {
		return DialogGraphView.class;
	}
}
