/*
* generated by Xtext
*/
package de.unidue.ecg.dialogScript.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.unidue.ecg.dialogScript.services.DialogScriptGrammarAccess;

public class DialogScriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DialogScriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.unidue.ecg.dialogScript.parser.antlr.internal.InternalDialogScriptParser createParser(XtextTokenStream stream) {
		return new de.unidue.ecg.dialogScript.parser.antlr.internal.InternalDialogScriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}
	
	public DialogScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DialogScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
