/*
* generated by Xtext
*/
package de.unidue.ecg.characterScript.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CharacterScriptAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/unidue/ecg/characterScript/parser/antlr/internal/InternalCharacterScript.tokens");
	}
}
