/*
* generated by Xtext
*/
package de.unidue.ecg.characterScript.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.unidue.ecg.characterScript.services.CharacterScriptGrammarAccess;

public class CharacterScriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CharacterScriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.unidue.ecg.characterScript.parser.antlr.internal.InternalCharacterScriptParser createParser(XtextTokenStream stream) {
		return new de.unidue.ecg.characterScript.parser.antlr.internal.InternalCharacterScriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Characters";
	}
	
	public CharacterScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CharacterScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
