/*
 * generated by Xtext
 */
package de.unidue.ecg.characterScript.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.unidue.ecg.characterScript.ui.internal.CharacterScriptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CharacterScriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CharacterScriptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CharacterScriptActivator.getInstance().getInjector(CharacterScriptActivator.DE_UNIDUE_ECG_CHARACTERSCRIPT_CHARACTERSCRIPT);
	}
	
}
