/**
 * generated by Xtext
 */
package de.unidue.ecg.dialogScript.ui.quickfix;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import de.unidue.ecg.common.linking.CustomLinkingDiagnosticMessageProvider;
import de.unidue.ecg.dialogScript.dialogScript.AbstractChoiceDialog;
import de.unidue.ecg.dialogScript.dialogScript.CharacterDefinition;
import de.unidue.ecg.dialogScript.dialogScript.CharactersDefintion;
import de.unidue.ecg.dialogScript.dialogScript.ConditionDefinition;
import de.unidue.ecg.dialogScript.dialogScript.ConditionList;
import de.unidue.ecg.dialogScript.dialogScript.Conditional;
import de.unidue.ecg.dialogScript.dialogScript.ConditionalBody;
import de.unidue.ecg.dialogScript.dialogScript.ConditionsDefinition;
import de.unidue.ecg.dialogScript.dialogScript.DialogLine;
import de.unidue.ecg.dialogScript.dialogScript.DialogScriptFactory;
import de.unidue.ecg.dialogScript.dialogScript.DialogScriptPackage;
import de.unidue.ecg.dialogScript.dialogScript.Exit;
import de.unidue.ecg.dialogScript.dialogScript.Hub;
import de.unidue.ecg.dialogScript.dialogScript.Modifier;
import de.unidue.ecg.dialogScript.dialogScript.Script;
import de.unidue.ecg.dialogScript.dialogScript.Switch;
import de.unidue.ecg.dialogScript.dialogScript.SwitchDefinition;
import de.unidue.ecg.dialogScript.dialogScript.SwitchList;
import de.unidue.ecg.dialogScript.dialogScript.SwitchOff;
import de.unidue.ecg.dialogScript.dialogScript.SwitchOn;
import de.unidue.ecg.dialogScript.dialogScript.SwitchValue;
import de.unidue.ecg.dialogScript.dialogScript.SwitchesDefinition;
import de.unidue.ecg.dialogScript.validation.DialogScriptValidator;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.diagnostics.Diagnostic;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class DialogScriptQuickfixProvider extends DefaultQuickfixProvider {
  @Inject
  private CustomLinkingDiagnosticMessageProvider customLinkingDiagnosticMessageProvider;
  
  /**
   * TODO: Check for programmatic execution of rename refactoring for these rename quickfixes
   */
  @Fix(DialogScriptValidator.WRONG_CONDTIONAL_USAGE)
  public void makeConditionSingle(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final ISemanticModification _function = new ISemanticModification() {
      public void apply(final EObject element, final IModificationContext context) throws Exception {
        String[] _data = issue.getData();
        String _get = _data[0];
        final int index = Integer.parseInt(_get);
        final Hub hub = ((Hub) element);
        EList<AbstractChoiceDialog> _choiceDialogs = hub.getChoiceDialogs();
        AbstractChoiceDialog _get_1 = _choiceDialogs.get(index);
        final Conditional conditional = ((Conditional) _get_1);
        EList<Modifier> _modifiers = conditional.getModifiers();
        _modifiers.add(Modifier.SINGLE);
      }
    };
    acceptor.accept(issue, "Add \'single\' modifier", "Add \'single\' modifier", null, _function);
  }
  
  @Fix(DialogScriptValidator.WRONG_CONDTIONAL_USAGE)
  public void addExitHubStatement(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final ISemanticModification _function = new ISemanticModification() {
      public void apply(final EObject element, final IModificationContext context) throws Exception {
        String[] _data = issue.getData();
        String _get = _data[0];
        final int index = Integer.parseInt(_get);
        final Hub hub = ((Hub) element);
        EList<AbstractChoiceDialog> _choiceDialogs = hub.getChoiceDialogs();
        AbstractChoiceDialog _get_1 = _choiceDialogs.get(index);
        final Conditional conditional = ((Conditional) _get_1);
        ConditionalBody _body = conditional.getBody();
        boolean _equals = Objects.equal(_body, null);
        if (_equals) {
          ConditionalBody _createConditionalBody = DialogScriptFactory.eINSTANCE.createConditionalBody();
          conditional.setBody(_createConditionalBody);
        }
        final Exit exit = DialogScriptFactory.eINSTANCE.createExit();
        exit.setExitHub(true);
        ConditionalBody _body_1 = conditional.getBody();
        _body_1.setJump(exit);
      }
    };
    acceptor.accept(issue, "Add \'exit hub\' statement", "Add \'exit hub\' statement", null, _function);
  }
  
  @Fix(Diagnostic.LINKING_DIAGNOSTIC)
  public void conditionUnknown(final Issue issue, final IssueResolutionAcceptor acceptor) {
    EClass _conditionDefinition = DialogScriptPackage.eINSTANCE.getConditionDefinition();
    String linkText = this.customLinkingDiagnosticMessageProvider.getLinkText(issue, _conditionDefinition);
    boolean _notEquals = (!Objects.equal(linkText, null));
    if (_notEquals) {
      String _plus = ("Create condition \'" + linkText);
      String _plus_1 = (_plus + "\'");
      String _plus_2 = ("Create condition \'" + linkText);
      String _plus_3 = (_plus_2 + "\'");
      final ISemanticModification _function = new ISemanticModification() {
        public void apply(final EObject element, final IModificationContext context) throws Exception {
          if ((element instanceof ConditionList)) {
            final Script root = EcoreUtil2.<Script>getContainerOfType(element, Script.class);
            final ConditionDefinition condition = DialogScriptFactory.eINSTANCE.createConditionDefinition();
            EClass _conditionDefinition = DialogScriptPackage.eINSTANCE.getConditionDefinition();
            String _linkText = DialogScriptQuickfixProvider.this.customLinkingDiagnosticMessageProvider.getLinkText(issue, _conditionDefinition);
            condition.setName(_linkText);
            final SwitchList switchList = DialogScriptFactory.eINSTANCE.createSwitchList();
            SwitchesDefinition _switchesDefinition = root.getSwitchesDefinition();
            boolean _equals = Objects.equal(_switchesDefinition, null);
            if (_equals) {
              final SwitchDefinition switch_ = DialogScriptFactory.eINSTANCE.createSwitchDefinition();
              switch_.setName("switch1");
              switch_.setValue(SwitchValue.OFF);
              SwitchesDefinition _createSwitchesDefinition = DialogScriptFactory.eINSTANCE.createSwitchesDefinition();
              root.setSwitchesDefinition(_createSwitchesDefinition);
              SwitchesDefinition _switchesDefinition_1 = root.getSwitchesDefinition();
              EList<SwitchDefinition> _switches = _switchesDefinition_1.getSwitches();
              _switches.add(switch_);
              final Switch switchRef = DialogScriptFactory.eINSTANCE.createSwitch();
              switchRef.setSwitch(switch_);
              switchRef.setValue(SwitchValue.OFF);
              EList<Switch> _switches_1 = switchList.getSwitches();
              _switches_1.add(switchRef);
            } else {
              SwitchesDefinition _switchesDefinition_2 = root.getSwitchesDefinition();
              EList<SwitchDefinition> _switches_2 = _switchesDefinition_2.getSwitches();
              final SwitchDefinition switch__1 = _switches_2.get(0);
              final Switch switchRef_1 = DialogScriptFactory.eINSTANCE.createSwitch();
              switchRef_1.setSwitch(switch__1);
              switchRef_1.setValue(SwitchValue.OFF);
              EList<Switch> _switches_3 = switchList.getSwitches();
              _switches_3.add(switchRef_1);
            }
            condition.setSwitchList(switchList);
            ConditionsDefinition _conditionsDefinition = root.getConditionsDefinition();
            boolean _equals_1 = Objects.equal(_conditionsDefinition, null);
            if (_equals_1) {
              ConditionsDefinition _createConditionsDefinition = DialogScriptFactory.eINSTANCE.createConditionsDefinition();
              root.setConditionsDefinition(_createConditionsDefinition);
            }
            ConditionsDefinition _conditionsDefinition_1 = root.getConditionsDefinition();
            EList<ConditionDefinition> _conditions = _conditionsDefinition_1.getConditions();
            _conditions.add(condition);
          }
        }
      };
      acceptor.accept(issue, _plus_1, _plus_3, 
        null, _function);
    }
  }
  
  @Fix(DialogScriptValidator.UNRESOLVED_CHARACTER)
  public void characterUnknown(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    final String linkText = _data[0];
    boolean _notEquals = (!Objects.equal(linkText, null));
    if (_notEquals) {
      String _plus = ("Add character \'" + linkText);
      String _plus_1 = (_plus + "\' to script");
      String _plus_2 = ("Add character \'" + linkText);
      String _plus_3 = (_plus_2 + "\' to script");
      final ISemanticModification _function = new ISemanticModification() {
        public void apply(final EObject element, final IModificationContext context) throws Exception {
          if ((element instanceof DialogLine)) {
            final Script root = EcoreUtil2.<Script>getContainerOfType(element, Script.class);
            final CharacterDefinition charaDef = DialogScriptFactory.eINSTANCE.createCharacterDefinition();
            charaDef.setImportedNamespace(linkText);
            CharactersDefintion _charactersDefinition = root.getCharactersDefinition();
            boolean _equals = Objects.equal(_charactersDefinition, null);
            if (_equals) {
              CharactersDefintion _createCharactersDefintion = DialogScriptFactory.eINSTANCE.createCharactersDefintion();
              root.setCharactersDefinition(_createCharactersDefintion);
            }
            CharactersDefintion _charactersDefinition_1 = root.getCharactersDefinition();
            EList<CharacterDefinition> _characters = _charactersDefinition_1.getCharacters();
            _characters.add(charaDef);
          }
        }
      };
      acceptor.accept(issue, _plus_1, _plus_3, null, _function);
    }
  }
  
  @Fix(Diagnostic.LINKING_DIAGNOSTIC)
  public void switchUnknown(final Issue issue, final IssueResolutionAcceptor acceptor) {
    EClass _switchDefinition = DialogScriptPackage.eINSTANCE.getSwitchDefinition();
    String linkText = this.customLinkingDiagnosticMessageProvider.getLinkText(issue, _switchDefinition);
    boolean _notEquals = (!Objects.equal(linkText, null));
    if (_notEquals) {
      String _plus = ("Create switch \'" + linkText);
      String _plus_1 = (_plus + "\'");
      String _plus_2 = ("Create switch \'" + linkText);
      String _plus_3 = (_plus_2 + "\'");
      final ISemanticModification _function = new ISemanticModification() {
        public void apply(final EObject element, final IModificationContext context) throws Exception {
          boolean _or = false;
          boolean _or_1 = false;
          if ((element instanceof SwitchOff)) {
            _or_1 = true;
          } else {
            _or_1 = ((element instanceof SwitchOff) || (element instanceof SwitchOn));
          }
          if (_or_1) {
            _or = true;
          } else {
            _or = (_or_1 || (element instanceof Switch));
          }
          if (_or) {
            final Script root = EcoreUtil2.<Script>getContainerOfType(element, Script.class);
            final SwitchDefinition switch_ = DialogScriptFactory.eINSTANCE.createSwitchDefinition();
            EClass _switchDefinition = DialogScriptPackage.eINSTANCE.getSwitchDefinition();
            String _linkText = DialogScriptQuickfixProvider.this.customLinkingDiagnosticMessageProvider.getLinkText(issue, _switchDefinition);
            switch_.setName(_linkText);
            switch_.setValue(SwitchValue.OFF);
            SwitchesDefinition _switchesDefinition = root.getSwitchesDefinition();
            boolean _equals = Objects.equal(_switchesDefinition, null);
            if (_equals) {
              SwitchesDefinition _createSwitchesDefinition = DialogScriptFactory.eINSTANCE.createSwitchesDefinition();
              root.setSwitchesDefinition(_createSwitchesDefinition);
            }
            SwitchesDefinition _switchesDefinition_1 = root.getSwitchesDefinition();
            EList<SwitchDefinition> _switches = _switchesDefinition_1.getSwitches();
            _switches.add(switch_);
          }
        }
      };
      acceptor.accept(issue, _plus_1, _plus_3, null, _function);
    }
  }
}
