/*
* generated by Xtext
*/
package de.unidue.ecg.dialogScript.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.unidue.ecg.dialogScript.services.DialogScriptGrammarAccess;

public class DialogScriptParser extends AbstractContentAssistParser {
	
	@Inject
	private DialogScriptGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.unidue.ecg.dialogScript.ui.contentassist.antlr.internal.InternalDialogScriptParser createParser() {
		de.unidue.ecg.dialogScript.ui.contentassist.antlr.internal.InternalDialogScriptParser result = new de.unidue.ecg.dialogScript.ui.contentassist.antlr.internal.InternalDialogScriptParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRecursiveAccess().getAlternatives(), "rule__Recursive__Alternatives");
					put(grammarAccess.getAbstractChoiceDialogAccess().getAlternatives(), "rule__AbstractChoiceDialog__Alternatives");
					put(grammarAccess.getJumpAccess().getAlternatives(), "rule__Jump__Alternatives");
					put(grammarAccess.getExitAccess().getAlternatives_2(), "rule__Exit__Alternatives_2");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getModifierAccess().getAlternatives(), "rule__Modifier__Alternatives");
					put(grammarAccess.getSwitchValueAccess().getAlternatives(), "rule__SwitchValue__Alternatives");
					put(grammarAccess.getScriptAccess().getGroup(), "rule__Script__Group__0");
					put(grammarAccess.getCharactersDefinitionAccess().getGroup(), "rule__CharactersDefinition__Group__0");
					put(grammarAccess.getCharactersDefinitionAccess().getGroup_3(), "rule__CharactersDefinition__Group_3__0");
					put(grammarAccess.getSwitchesDefinitionAccess().getGroup(), "rule__SwitchesDefinition__Group__0");
					put(grammarAccess.getSwitchesDefinitionAccess().getGroup_3(), "rule__SwitchesDefinition__Group_3__0");
					put(grammarAccess.getSwitchDefinitionAccess().getGroup(), "rule__SwitchDefinition__Group__0");
					put(grammarAccess.getSwitchDefinitionAccess().getGroup_1(), "rule__SwitchDefinition__Group_1__0");
					put(grammarAccess.getConditionsDefinitionAccess().getGroup(), "rule__ConditionsDefinition__Group__0");
					put(grammarAccess.getConditionDefinitionAccess().getGroup(), "rule__ConditionDefinition__Group__0");
					put(grammarAccess.getSceneAccess().getGroup(), "rule__Scene__Group__0");
					put(grammarAccess.getDialogAccess().getGroup(), "rule__Dialog__Group__0");
					put(grammarAccess.getDefaultsAccess().getGroup(), "rule__Defaults__Group__0");
					put(grammarAccess.getFirstTimeAccess().getGroup(), "rule__FirstTime__Group__0");
					put(grammarAccess.getOtherTimesAccess().getGroup(), "rule__OtherTimes__Group__0");
					put(grammarAccess.getPartingLinesAccess().getGroup(), "rule__PartingLines__Group__0");
					put(grammarAccess.getHubAccess().getGroup(), "rule__Hub__Group__0");
					put(grammarAccess.getConditionalChoiceDialogAccess().getGroup(), "rule__ConditionalChoiceDialog__Group__0");
					put(grammarAccess.getOtherwiseChoiceAccess().getGroup(), "rule__OtherwiseChoice__Group__0");
					put(grammarAccess.getOtherwiseChoiceAccess().getGroup_3(), "rule__OtherwiseChoice__Group_3__0");
					put(grammarAccess.getChoiceDialogAccess().getGroup(), "rule__ChoiceDialog__Group__0");
					put(grammarAccess.getConditionListAccess().getGroup(), "rule__ConditionList__Group__0");
					put(grammarAccess.getConditionListAccess().getGroup_1(), "rule__ConditionList__Group_1__0");
					put(grammarAccess.getInvokeHubAccess().getGroup(), "rule__InvokeHub__Group__0");
					put(grammarAccess.getInvokeSceneAccess().getGroup(), "rule__InvokeScene__Group__0");
					put(grammarAccess.getExitAccess().getGroup(), "rule__Exit__Group__0");
					put(grammarAccess.getConditionalAccess().getGroup(), "rule__Conditional__Group__0");
					put(grammarAccess.getSwitchListAccess().getGroup(), "rule__SwitchList__Group__0");
					put(grammarAccess.getSwitchListAccess().getGroup_1(), "rule__SwitchList__Group_1__0");
					put(grammarAccess.getSwitchAccess().getGroup(), "rule__Switch__Group__0");
					put(grammarAccess.getConditionalBodyAccess().getGroup(), "rule__ConditionalBody__Group__0");
					put(grammarAccess.getOtherwiseAccess().getGroup(), "rule__Otherwise__Group__0");
					put(grammarAccess.getOtherwiseAccess().getGroup_2(), "rule__Otherwise__Group_2__0");
					put(grammarAccess.getSwitchOffAccess().getGroup(), "rule__SwitchOff__Group__0");
					put(grammarAccess.getSwitchOffAccess().getGroup_3(), "rule__SwitchOff__Group_3__0");
					put(grammarAccess.getSwitchOnAccess().getGroup(), "rule__SwitchOn__Group__0");
					put(grammarAccess.getSwitchOnAccess().getGroup_3(), "rule__SwitchOn__Group_3__0");
					put(grammarAccess.getDialogLineAccess().getGroup(), "rule__DialogLine__Group__0");
					put(grammarAccess.getScriptAccess().getCharactersDefinitionAssignment_1(), "rule__Script__CharactersDefinitionAssignment_1");
					put(grammarAccess.getScriptAccess().getSwitchesDefinitionAssignment_2(), "rule__Script__SwitchesDefinitionAssignment_2");
					put(grammarAccess.getScriptAccess().getConditionsDefinitionAssignment_3(), "rule__Script__ConditionsDefinitionAssignment_3");
					put(grammarAccess.getScriptAccess().getScenesAssignment_4(), "rule__Script__ScenesAssignment_4");
					put(grammarAccess.getCharactersDefinitionAccess().getCharactersAssignment_2(), "rule__CharactersDefinition__CharactersAssignment_2");
					put(grammarAccess.getCharactersDefinitionAccess().getCharactersAssignment_3_1(), "rule__CharactersDefinition__CharactersAssignment_3_1");
					put(grammarAccess.getCharacterDefinitionAccess().getNameAssignment(), "rule__CharacterDefinition__NameAssignment");
					put(grammarAccess.getSwitchesDefinitionAccess().getSwitchesAssignment_2(), "rule__SwitchesDefinition__SwitchesAssignment_2");
					put(grammarAccess.getSwitchesDefinitionAccess().getSwitchesAssignment_3_1(), "rule__SwitchesDefinition__SwitchesAssignment_3_1");
					put(grammarAccess.getSwitchDefinitionAccess().getNameAssignment_0(), "rule__SwitchDefinition__NameAssignment_0");
					put(grammarAccess.getSwitchDefinitionAccess().getValueAssignment_1_1(), "rule__SwitchDefinition__ValueAssignment_1_1");
					put(grammarAccess.getConditionsDefinitionAccess().getConditionsAssignment_1(), "rule__ConditionsDefinition__ConditionsAssignment_1");
					put(grammarAccess.getConditionsDefinitionAccess().getConditionsAssignment_2(), "rule__ConditionsDefinition__ConditionsAssignment_2");
					put(grammarAccess.getConditionDefinitionAccess().getNameAssignment_1(), "rule__ConditionDefinition__NameAssignment_1");
					put(grammarAccess.getConditionDefinitionAccess().getSwitchListAssignment_3(), "rule__ConditionDefinition__SwitchListAssignment_3");
					put(grammarAccess.getSceneAccess().getNameAssignment_2(), "rule__Scene__NameAssignment_2");
					put(grammarAccess.getSceneAccess().getDialogAssignment_3(), "rule__Scene__DialogAssignment_3");
					put(grammarAccess.getDialogAccess().getDefaultsAssignment_1(), "rule__Dialog__DefaultsAssignment_1");
					put(grammarAccess.getDialogAccess().getFirstTimeAssignment_2(), "rule__Dialog__FirstTimeAssignment_2");
					put(grammarAccess.getDialogAccess().getRecursivesAssignment_3(), "rule__Dialog__RecursivesAssignment_3");
					put(grammarAccess.getDialogAccess().getPartingLinesAssignment_4(), "rule__Dialog__PartingLinesAssignment_4");
					put(grammarAccess.getDefaultsAccess().getCommentAssignment_2(), "rule__Defaults__CommentAssignment_2");
					put(grammarAccess.getDefaultsAccess().getBodyAssignment_3(), "rule__Defaults__BodyAssignment_3");
					put(grammarAccess.getFirstTimeAccess().getCommentAssignment_3(), "rule__FirstTime__CommentAssignment_3");
					put(grammarAccess.getFirstTimeAccess().getBodyAssignment_4(), "rule__FirstTime__BodyAssignment_4");
					put(grammarAccess.getFirstTimeAccess().getOtherTimesAssignment_5(), "rule__FirstTime__OtherTimesAssignment_5");
					put(grammarAccess.getOtherTimesAccess().getCommentAssignment_2(), "rule__OtherTimes__CommentAssignment_2");
					put(grammarAccess.getOtherTimesAccess().getBodyAssignment_3(), "rule__OtherTimes__BodyAssignment_3");
					put(grammarAccess.getPartingLinesAccess().getCommentAssignment_2(), "rule__PartingLines__CommentAssignment_2");
					put(grammarAccess.getPartingLinesAccess().getBodyAssignment_3(), "rule__PartingLines__BodyAssignment_3");
					put(grammarAccess.getHubAccess().getIsHiddenAssignment_0(), "rule__Hub__IsHiddenAssignment_0");
					put(grammarAccess.getHubAccess().getNameAssignment_2(), "rule__Hub__NameAssignment_2");
					put(grammarAccess.getHubAccess().getHubCommentAssignment_3(), "rule__Hub__HubCommentAssignment_3");
					put(grammarAccess.getHubAccess().getChoiceDialogsAssignment_4(), "rule__Hub__ChoiceDialogsAssignment_4");
					put(grammarAccess.getConditionalChoiceDialogAccess().getModifiersAssignment_0(), "rule__ConditionalChoiceDialog__ModifiersAssignment_0");
					put(grammarAccess.getConditionalChoiceDialogAccess().getConditionListAssignment_4(), "rule__ConditionalChoiceDialog__ConditionListAssignment_4");
					put(grammarAccess.getConditionalChoiceDialogAccess().getCommentAssignment_6(), "rule__ConditionalChoiceDialog__CommentAssignment_6");
					put(grammarAccess.getConditionalChoiceDialogAccess().getChoiceDialogsAssignment_7(), "rule__ConditionalChoiceDialog__ChoiceDialogsAssignment_7");
					put(grammarAccess.getConditionalChoiceDialogAccess().getOtherwiseChoicesAssignment_8(), "rule__ConditionalChoiceDialog__OtherwiseChoicesAssignment_8");
					put(grammarAccess.getOtherwiseChoiceAccess().getModifiersAssignment_0(), "rule__OtherwiseChoice__ModifiersAssignment_0");
					put(grammarAccess.getOtherwiseChoiceAccess().getConditionListAssignment_3_2(), "rule__OtherwiseChoice__ConditionListAssignment_3_2");
					put(grammarAccess.getOtherwiseChoiceAccess().getCommentAssignment_4(), "rule__OtherwiseChoice__CommentAssignment_4");
					put(grammarAccess.getOtherwiseChoiceAccess().getChoicesAssignment_5(), "rule__OtherwiseChoice__ChoicesAssignment_5");
					put(grammarAccess.getChoiceDialogAccess().getModifiersAssignment_1(), "rule__ChoiceDialog__ModifiersAssignment_1");
					put(grammarAccess.getChoiceDialogAccess().getNameAssignment_3(), "rule__ChoiceDialog__NameAssignment_3");
					put(grammarAccess.getChoiceDialogAccess().getChoiceCommentAssignment_4(), "rule__ChoiceDialog__ChoiceCommentAssignment_4");
					put(grammarAccess.getChoiceDialogAccess().getBodyAssignment_5(), "rule__ChoiceDialog__BodyAssignment_5");
					put(grammarAccess.getConditionListAccess().getConditionsAssignment_0(), "rule__ConditionList__ConditionsAssignment_0");
					put(grammarAccess.getConditionListAccess().getConditionsAssignment_1_1(), "rule__ConditionList__ConditionsAssignment_1_1");
					put(grammarAccess.getInvokeHubAccess().getHubAssignment_2(), "rule__InvokeHub__HubAssignment_2");
					put(grammarAccess.getInvokeSceneAccess().getSceneAssignment_2(), "rule__InvokeScene__SceneAssignment_2");
					put(grammarAccess.getExitAccess().getExitHubAssignment_2_0(), "rule__Exit__ExitHubAssignment_2_0");
					put(grammarAccess.getExitAccess().getExitSceneAssignment_2_1(), "rule__Exit__ExitSceneAssignment_2_1");
					put(grammarAccess.getConditionalAccess().getModifiersAssignment_0(), "rule__Conditional__ModifiersAssignment_0");
					put(grammarAccess.getConditionalAccess().getConditionListAssignment_3(), "rule__Conditional__ConditionListAssignment_3");
					put(grammarAccess.getConditionalAccess().getCommentAssignment_5(), "rule__Conditional__CommentAssignment_5");
					put(grammarAccess.getConditionalAccess().getBodyAssignment_6(), "rule__Conditional__BodyAssignment_6");
					put(grammarAccess.getConditionalAccess().getOtherwiseListAssignment_7(), "rule__Conditional__OtherwiseListAssignment_7");
					put(grammarAccess.getSwitchListAccess().getSwitchesAssignment_0(), "rule__SwitchList__SwitchesAssignment_0");
					put(grammarAccess.getSwitchListAccess().getSwitchesAssignment_1_1(), "rule__SwitchList__SwitchesAssignment_1_1");
					put(grammarAccess.getSwitchAccess().getSwitchAssignment_0(), "rule__Switch__SwitchAssignment_0");
					put(grammarAccess.getSwitchAccess().getValueAssignment_2(), "rule__Switch__ValueAssignment_2");
					put(grammarAccess.getConditionalBodyAccess().getStatementsAssignment_1(), "rule__ConditionalBody__StatementsAssignment_1");
					put(grammarAccess.getConditionalBodyAccess().getSwitchOnAssignment_2(), "rule__ConditionalBody__SwitchOnAssignment_2");
					put(grammarAccess.getConditionalBodyAccess().getSwitchOffAssignment_3(), "rule__ConditionalBody__SwitchOffAssignment_3");
					put(grammarAccess.getConditionalBodyAccess().getJumpAssignment_4(), "rule__ConditionalBody__JumpAssignment_4");
					put(grammarAccess.getOtherwiseAccess().getModifiersAssignment_0(), "rule__Otherwise__ModifiersAssignment_0");
					put(grammarAccess.getOtherwiseAccess().getConditionListAssignment_2_2(), "rule__Otherwise__ConditionListAssignment_2_2");
					put(grammarAccess.getOtherwiseAccess().getCommentAssignment_3(), "rule__Otherwise__CommentAssignment_3");
					put(grammarAccess.getOtherwiseAccess().getBodyAssignment_4(), "rule__Otherwise__BodyAssignment_4");
					put(grammarAccess.getSwitchOffAccess().getSetsAssignment_2(), "rule__SwitchOff__SetsAssignment_2");
					put(grammarAccess.getSwitchOffAccess().getSetsAssignment_3_1(), "rule__SwitchOff__SetsAssignment_3_1");
					put(grammarAccess.getSwitchOffAccess().getCommentAssignment_4(), "rule__SwitchOff__CommentAssignment_4");
					put(grammarAccess.getSwitchOnAccess().getSetsAssignment_2(), "rule__SwitchOn__SetsAssignment_2");
					put(grammarAccess.getSwitchOnAccess().getSetsAssignment_3_1(), "rule__SwitchOn__SetsAssignment_3_1");
					put(grammarAccess.getSwitchOnAccess().getCommentAssignment_4(), "rule__SwitchOn__CommentAssignment_4");
					put(grammarAccess.getDialogLineAccess().getCharacterAssignment_0(), "rule__DialogLine__CharacterAssignment_0");
					put(grammarAccess.getDialogLineAccess().getLinesAssignment_2(), "rule__DialogLine__LinesAssignment_2");
					put(grammarAccess.getDialogLineAccess().getCommentAssignment_3(), "rule__DialogLine__CommentAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.unidue.ecg.dialogScript.ui.contentassist.antlr.internal.InternalDialogScriptParser typedParser = (de.unidue.ecg.dialogScript.ui.contentassist.antlr.internal.InternalDialogScriptParser) parser;
			typedParser.entryRuleScript();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DialogScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DialogScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
