/**
 * generated by Xtext
 */
package de.unidue.ecg.dialogScript.ui.outline;

import de.unidue.ecg.dialogScript.dialogScript.Dialog;
import de.unidue.ecg.dialogScript.dialogScript.Otherwise;
import de.unidue.ecg.dialogScript.dialogScript.Switch;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class DialogScriptOutlineTreeProvider extends DefaultOutlineTreeProvider {
  protected void _createNode(final IOutlineNode parentNode, final Switch switch_) {
    this._createChildren(parentNode, switch_);
  }
  
  protected void _createNode(final IOutlineNode parentNode, final Otherwise otherwise) {
    this._createChildren(parentNode, otherwise);
  }
  
  protected void _createNode(final IOutlineNode parentNode, final Dialog dialog) {
    this._createChildren(parentNode, dialog);
  }
}
