/**
 * generated by Xtext
 */
package de.unidue.ecg.characterScript.formatting;

import com.google.inject.Inject;
import de.unidue.ecg.characterScript.services.CharacterScriptGrammarAccess;
import de.unidue.ecg.characterScript.services.CharacterScriptGrammarAccess.CharacterElements;
import de.unidue.ecg.characterScript.services.CharacterScriptGrammarAccess.CharactersElements;
import de.unidue.ecg.characterScript.services.CharacterScriptGrammarAccess.TemplateElements;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.formatting.impl.FormattingConfig.LinewrapLocator;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
@SuppressWarnings("all")
public class CharacterScriptFormatter extends AbstractDeclarativeFormatter {
  @Inject
  @Extension
  private CharacterScriptGrammarAccess _characterScriptGrammarAccess;
  
  protected void configureFormatting(final FormattingConfig c) {
    LinewrapLocator _setLinewrap = c.setLinewrap(0, 1, 2);
    TerminalRule _sL_COMMENTRule = this._characterScriptGrammarAccess.getSL_COMMENTRule();
    _setLinewrap.before(_sL_COMMENTRule);
    LinewrapLocator _setLinewrap_1 = c.setLinewrap(0, 1, 2);
    TerminalRule _mL_COMMENTRule = this._characterScriptGrammarAccess.getML_COMMENTRule();
    _setLinewrap_1.before(_mL_COMMENTRule);
    LinewrapLocator _setLinewrap_2 = c.setLinewrap(0, 1, 1);
    TerminalRule _mL_COMMENTRule_1 = this._characterScriptGrammarAccess.getML_COMMENTRule();
    _setLinewrap_2.after(_mL_COMMENTRule_1);
    LinewrapLocator _setLinewrap_3 = c.setLinewrap();
    CharactersElements _charactersAccess = this._characterScriptGrammarAccess.getCharactersAccess();
    Assignment _importsAssignment_0 = _charactersAccess.getImportsAssignment_0();
    _setLinewrap_3.after(_importsAssignment_0);
    LinewrapLocator _setLinewrap_4 = c.setLinewrap();
    CharactersElements _charactersAccess_1 = this._characterScriptGrammarAccess.getCharactersAccess();
    RuleCall _importsImportParserRuleCall_0_0 = _charactersAccess_1.getImportsImportParserRuleCall_0_0();
    _setLinewrap_4.after(_importsImportParserRuleCall_0_0);
    LinewrapLocator _setLinewrap_5 = c.setLinewrap(2);
    TemplateElements _templateAccess = this._characterScriptGrammarAccess.getTemplateAccess();
    Keyword _templateKeyword_0 = _templateAccess.getTemplateKeyword_0();
    _setLinewrap_5.before(_templateKeyword_0);
    TemplateElements _templateAccess_1 = this._characterScriptGrammarAccess.getTemplateAccess();
    Assignment _nameAssignment_1 = _templateAccess_1.getNameAssignment_1();
    TemplateElements _templateAccess_2 = this._characterScriptGrammarAccess.getTemplateAccess();
    Keyword _endKeyword_4 = _templateAccess_2.getEndKeyword_4();
    c.setIndentation(_nameAssignment_1, _endKeyword_4);
    LinewrapLocator _setLinewrap_6 = c.setLinewrap();
    TemplateElements _templateAccess_3 = this._characterScriptGrammarAccess.getTemplateAccess();
    Keyword _endKeyword_4_1 = _templateAccess_3.getEndKeyword_4();
    _setLinewrap_6.before(_endKeyword_4_1);
    LinewrapLocator _setLinewrap_7 = c.setLinewrap();
    TemplateElements _templateAccess_4 = this._characterScriptGrammarAccess.getTemplateAccess();
    Assignment _defaultsAssignment_2 = _templateAccess_4.getDefaultsAssignment_2();
    _setLinewrap_7.before(_defaultsAssignment_2);
    LinewrapLocator _setLinewrap_8 = c.setLinewrap();
    TemplateElements _templateAccess_5 = this._characterScriptGrammarAccess.getTemplateAccess();
    Assignment _customsAssignment_3 = _templateAccess_5.getCustomsAssignment_3();
    _setLinewrap_8.before(_customsAssignment_3);
    LinewrapLocator _setLinewrap_9 = c.setLinewrap();
    CharacterElements _characterAccess = this._characterScriptGrammarAccess.getCharacterAccess();
    RuleCall _propertiesPropertyParserRuleCall_3_0 = _characterAccess.getPropertiesPropertyParserRuleCall_3_0();
    _setLinewrap_9.before(_propertiesPropertyParserRuleCall_3_0);
    CharacterElements _characterAccess_1 = this._characterScriptGrammarAccess.getCharacterAccess();
    Assignment _nameAssignment_1_1 = _characterAccess_1.getNameAssignment_1();
    CharacterElements _characterAccess_2 = this._characterScriptGrammarAccess.getCharacterAccess();
    Keyword _endKeyword_4_2 = _characterAccess_2.getEndKeyword_4();
    c.setIndentation(_nameAssignment_1_1, _endKeyword_4_2);
    LinewrapLocator _setLinewrap_10 = c.setLinewrap();
    CharacterElements _characterAccess_3 = this._characterScriptGrammarAccess.getCharacterAccess();
    Keyword _endKeyword_4_3 = _characterAccess_3.getEndKeyword_4();
    _setLinewrap_10.before(_endKeyword_4_3);
    LinewrapLocator _setLinewrap_11 = c.setLinewrap(2);
    CharacterElements _characterAccess_4 = this._characterScriptGrammarAccess.getCharacterAccess();
    Keyword _characterKeyword_0 = _characterAccess_4.getCharacterKeyword_0();
    _setLinewrap_11.before(_characterKeyword_0);
    LinewrapLocator _setLinewrap_12 = c.setLinewrap();
    CharacterElements _characterAccess_5 = this._characterScriptGrammarAccess.getCharacterAccess();
    Assignment _propertiesAssignment_3 = _characterAccess_5.getPropertiesAssignment_3();
    _setLinewrap_12.after(_propertiesAssignment_3);
  }
}
